import SequentCalculus.Finset
import SequentCalculus.Propositional.Syntax
import SequentCalculus.Propositional.LJ.Sequent
import SequentCalculus.Propositional.LJ.Semantics
import SequentCalculus.Propositional.LK.Sequent
